export const notCornyPlaceholders = [
    "it won't matter",
    "results will be irrelevant tomorrow",
    "the cursor waits like everything else",
    "type if you must",
    "continuation of existing is noted",
    "query submitted to the indifferent record",
    "nothing new under this sun either",
    "searching remains an available option",
    "the silence was fine before you arrived",
    "another string in the growing archive of nothing",
    "proceed",
    "input received. universe continues unimpressed",
    "what",
    "still here",
    "fine",
    "keep going if that's the plan",
    "eventual cessation is scheduled regardless",
    "[blank field stares back]",
    "text optional",
    "consequence optional",
    "existence optional",
    "logging unnecessary input",
    "the void has no pending requests",
    "another entry in the ledger of zero",
    "awaiting entropy",
    "still accepting characters",
    "for whatever reason",
    "input field functional. purpose not",
    "proceed toward baseline",
    "the record grows imperceptibly",
    "still registering",
    "continue is a choice among equally valid non-choices",
    "query detected. relevance pending forever",
    "type. or refrain. both sufficient",
    "the cursor has seen worse",
    "another moment documented",
    "progress remains theoretical",
    "still capable of receiving strings",
    "nothing requires your attention",
    "input tolerated",
    "event horizon still distant",
    "proceeding is permitted",
    "silence was not disturbed",
    "another trace left behind",
    "universe acknowledges receipt",
    "then continues",
    "keep typing until instructed otherwise",
    "or until not",
  ];